she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(),name='newStory'),
    path('<int:pk>/edit', views.EditStoryView.as_view(), name='editStory'),
    path('all-stories/', views.All_stories_View.as_view(), name='allstories' ),
    path('authors/<int:pk>/stories', views.AuthorStories.as_view(), name= 'authorstories' ),
   path('<int:pk>/delete', views.DeleteStoryView.as_view(), name='deleteStory')
    ]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls'))
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, EditAccountView, ProfileView

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/edit', EditAccountView.as_view(), name='editAccount'),
    # path('password/', PasswordChangeView.as_view(Template_name='registration/change-password.html'))
]

she_codes_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class NewsStory(models.Model):
    class Meta:
        ordering =['-pub_date'] 
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url_field = models.URLField(max_length=200, null=True)

    def get_absolute_url(self):
     return reverse('news:story',kwargs={'pk': self.pk})

she_codes_news/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
class CustomUser(AbstractUser):
    name = models.CharField (max_length=200, blank=True, null=True)
    bio = models.TextField (max_length=200, blank=True, null=True)
    email = models.CharField (max_length=200, blank=True, null=True)
    profile_picture = models.URLField  (blank=True, null=True)
    linkedin = models.URLField  (blank=True, null=True)
    instagram = models.URLField  (blank=True, null=True)
    github = models.URLField  (blank=True, null=True)
    
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta:
        model = NewsStory 
        fields = ['title', 'pub_date', 'content','image_url_field']
        widgets = {
            'pub_date': forms.DateInput(format=('%m/%d/%Y'),attrs={'class':'form-control', 'placeholder':'Select a date','type':'date'}),
            }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio', 'profile_picture','linkedin','instagram', 'github']
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'bio', 'profile_picture','linkedin','instagram', 'github']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')[:4]
        return context
class EditStoryView(generic.UpdateView):
    form_class = StoryForm
    model = NewsStory
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html' 

class All_stories_View(generic.ListView):
    template_name = 'news/allstories.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.all().order_by('-pub_date')
        return context

class AuthorStories (generic.ListView): 
    template_name = 'news/authorstories.html'
    context_object_name = 'stories'

    def get_queryset(self):
       return NewsStory.objects.filter(author=self.kwargs['pk'])
       
class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    context_object_name = 'story'
    template_name = 'news/deleteStory.html' 
    success_url = reverse_lazy('news:index')

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm
from news.models import NewsStory
class CreateAccountView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'users/createAccount.html'
class ProfileView(generic.DetailView):
    model = CustomUser
    template_name = 'users/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_stories'] = NewsStory.objects.filter(author=self.kwargs['pk'])
        return context
class EditAccountView(generic.UpdateView):
    form_class = CustomUserChangeForm
    model = CustomUser
    context_object_name = 'createAccount'
    template_name = 'users/createAccount.html'
    def get_success_url(self): 
         return reverse_lazy('users:profile', kwargs={'pk': self.object.id})

she_codes_news/news/templates/news/allstories.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<h2> Welcome {{ user.username }}</h2>
    <h2>All Stories</h2>
    <div id="latest_stories">
        {% if all_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    
{% endblock %}

she_codes_news/news/templates/news/authorstories.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<h2>Author Stories</h2>
    <h2>All Stories</h2>
    <div id="latest_stories">
        {% if stories %}
            {% for story in stories %}
                {% include "./storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    
{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<form class= "create-story-form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="button1" type="submit" value="submit">
    </form>
{% else %}
    <div>
        <h2> You need to be logged in to create a story </h2>
    </div>
    <a href="{% url 'users:createAccount' %}"><button class="button1">CREATE ACCOUNT</a>
    <a href="{% url 'login'%}"><button class="button1">LOGIN</a>
{% endif %}


{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ story.title }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endif %}
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<h2> Welcome {{ user.username }}</h2>
<a href="{% url 'news:newStory' %}">Write New Story</a>
<a href="{% url 'news:allstories' %}">All Stories</a>

    <h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
            {% include "./storyCard.html" with story=story position=forloop.counter %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div id="story-wrapper">
    
{% if story.author == request.user %}
<a href=" {% url 'news:editStory' story.id %}">Edit Story</a> 
<a href=" {% url 'news:deleteStory' story.id %}">Delete Story</a>
{% endif %}
    <h2>{{ story.title }}</h2>
    <a href="{% url 'news:authorstories' story.author.id %}"><h4>{{ story.author }}</h4> </a>
    <div id="story-content">
        <img src="{{ story.image_url_field}}">
        {{ story.content|linebreaks }}
    </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        <!-- {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src= "{{ story.image_url_field}}">
        {% endif %} -->
        {% if story.image_url_field %}
            <img src="{{ story.image_url_field}}">
    
        {% else %}
            <img src="https://picsum.photos/300?random={{ story.id }}">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Jona Peh">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
            {% block stylesheets %}{% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            {% include './nav.html' %}
            <!-- include nav here -->
        </header>
        {% block content %}{% endblock %}
        <!-- content blocks here -->
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
      <a href="{% url 'users:profile' request.user.id %}">{{ user.username }}</a>
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'users:createAccount'%}">Create Account</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create Account</button>
</form>
{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>

<p> Username: {{user.username}}</p>
<p> Email: {{user.email}}</p>
<p> Profile Picture: <img src="{{ user.profile_picture}}"> </p>
<a href="{% url 'users:editAccount' request.user.id %}">Edit Account</a>
<p> Stories: </p>

    <div id="all-stories">
        {% if user_stories %}
            {% for story in user_stories %}
                {% include "news/storyCard.html" with story=story %}
                <!-- <p>{{ story.title }}</p> -->
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}